// <auto-generated />
namespace VoceViuMeuVeiculo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Criacaotabelas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criacaotabelas));
        
        string IMigrationMetadata.Id
        {
            get { return "201702062212372_Criacao-tabelas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
